# name属性用来指定这个工作流的名字
name: release CI
on:
  # 当对分支main进行push操作的时候,触发该条工作流
  push:
    branches: [ main ]
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 读取当前版本号
      id: version
      uses: ./
      with:
        path: 'package.json'
        prop_path: 'version'
    - name: 创建GitHub Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.value }}
        release_name: ${{ steps.version.outputs.value }}
        draft: false
        prerelease: false
